export const seedFoods = [
  {
    id: "common:magerquark",
    name: "Magerquark",
    brand: "Standard",
    caloriesPer100g: 67,
    proteinPer100g: 12,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    aliases: ["mager quark", "quark"],
  },
  {
    id: "brand:milbona-magerquark",
    name: "Magerquark",
    brand: "Milbona",
    caloriesPer100g: 67,
    proteinPer100g: 12,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    aliases: ["magerquark", "mager quark", "quark", "lidl magerquark"],
  },
  {
    id: "brand:ja-magerquark",
    name: "Magerquark",
    brand: "ja!",
    caloriesPer100g: 68,
    proteinPer100g: 12,
    carbsPer100g: 4.1,
    fatPer100g: 0.2,
    aliases: ["magerquark", "mager quark", "quark", "rewe magerquark"],
  },
  {
    id: "brand:gut-guenstig-magerquark",
    name: "Magerquark",
    brand: "Gut & Günstig",
    caloriesPer100g: 67,
    proteinPer100g: 12,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    aliases: ["magerquark", "mager quark", "quark", "edeka magerquark"],
  },
  {
    id: "brand:exquisa-quark-creme-0-2",
    name: "Quark Creme 0,2%",
    brand: "Exquisa",
    caloriesPer100g: 68,
    proteinPer100g: 12,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    aliases: ["magerquark", "mager quark", "quark", "exquisa magerquark"],
  },
  {
    id: "common:koerniger-frischkaese",
    name: "Körniger Frischkäse",
    brand: "Standard",
    caloriesPer100g: 98,
    proteinPer100g: 12,
    carbsPer100g: 3,
    fatPer100g: 4,
    aliases: ["körniger frischkäse", "koerniger frischkaese", "körni", "koerni", "hüttenkäse", "huettenkaese", "cottage cheese"],
  },
  {
    id: "brand:exquisa-koerniger-frischkaese-fitline",
    name: "Körniger Frischkäse Fitline",
    brand: "Exquisa",
    caloriesPer100g: 72,
    proteinPer100g: 13,
    carbsPer100g: 3.2,
    fatPer100g: 0.8,
    aliases: ["körniger frischkäse", "koerniger frischkaese", "hüttenkäse", "huettenkaese", "cottage cheese", "exquisa körniger"],
  },
  {
    id: "brand:milbona-koerniger-frischkaese-light",
    name: "Körniger Frischkäse light",
    brand: "Milbona",
    caloriesPer100g: 75,
    proteinPer100g: 12,
    carbsPer100g: 3,
    fatPer100g: 1.5,
    aliases: ["körniger frischkäse", "koerniger frischkaese", "hüttenkäse", "huettenkaese", "cottage cheese", "lidl körniger"],
  },
  {
    id: "brand:ja-koerniger-frischkaese",
    name: "Körniger Frischkäse",
    brand: "ja!",
    caloriesPer100g: 93,
    proteinPer100g: 12,
    carbsPer100g: 3.5,
    fatPer100g: 3.5,
    aliases: ["körniger frischkäse", "koerniger frischkaese", "hüttenkäse", "huettenkaese", "cottage cheese", "rewe körniger"],
  },
  {
    id: "brand:rewe-bio-koerniger-frischkaese",
    name: "Körniger Frischkäse",
    brand: "REWE Bio",
    caloriesPer100g: 96,
    proteinPer100g: 12,
    carbsPer100g: 3.4,
    fatPer100g: 3.8,
    aliases: ["körniger frischkäse", "koerniger frischkaese", "hüttenkäse", "huettenkaese", "cottage cheese", "bio körniger"],
  },
  {
    id: "brand:gervais-huettenkaese",
    name: "Hüttenkäse",
    brand: "Gervais",
    caloriesPer100g: 98,
    proteinPer100g: 12.5,
    carbsPer100g: 2.5,
    fatPer100g: 4.2,
    aliases: ["körniger frischkäse", "koerniger frischkaese", "hüttenkäse", "huettenkaese", "cottage cheese", "gervais körniger"],
  },
  {
    id: "brand:goldsteig-koerniger-frischkaese",
    name: "Körniger Frischkäse",
    brand: "Goldsteig",
    caloriesPer100g: 97,
    proteinPer100g: 12.4,
    carbsPer100g: 3,
    fatPer100g: 4,
    aliases: ["körniger frischkäse", "koerniger frischkaese", "hüttenkäse", "huettenkaese", "cottage cheese", "goldsteig körniger"],
  },
  {
    id: "common:skyr-natur",
    name: "Skyr natur",
    brand: "Standard",
    caloriesPer100g: 62,
    proteinPer100g: 11,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    aliases: ["skyr"],
  },
  {
    id: "brand:milbona-skyr-natur",
    name: "Skyr Natur",
    brand: "Milbona",
    caloriesPer100g: 62,
    proteinPer100g: 11,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    aliases: ["skyr", "lidl skyr", "skyr natur"],
  },
  {
    id: "brand:arla-skyr-natur",
    name: "Skyr Natur",
    brand: "Arla",
    caloriesPer100g: 63,
    proteinPer100g: 11,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    aliases: ["skyr", "arla skyr", "skyr natur"],
  },
  {
    id: "brand:ja-skyr-natur",
    name: "Skyr Natur",
    brand: "ja!",
    caloriesPer100g: 62,
    proteinPer100g: 11,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    aliases: ["skyr", "rewe skyr", "skyr natur"],
  },
  {
    id: "brand:gut-guenstig-skyr-natur",
    name: "Skyr Natur",
    brand: "Gut & Günstig",
    caloriesPer100g: 62,
    proteinPer100g: 11,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    aliases: ["skyr", "edeka skyr", "skyr natur"],
  },
  {
    id: "common:joghurt-natur",
    name: "Joghurt natur 1,5%",
    brand: "Standard",
    caloriesPer100g: 57,
    proteinPer100g: 4.3,
    carbsPer100g: 5.5,
    fatPer100g: 1.5,
    aliases: ["joghurt", "jogurt"],
  },
  {
    id: "brand:milbona-joghurt-natur-1-5",
    name: "Joghurt natur 1,5%",
    brand: "Milbona",
    caloriesPer100g: 57,
    proteinPer100g: 4.3,
    carbsPer100g: 5.5,
    fatPer100g: 1.5,
    aliases: ["joghurt", "jogurt", "lidl joghurt", "naturjoghurt"],
  },
  {
    id: "brand:ja-joghurt-natur-1-5",
    name: "Joghurt natur 1,5%",
    brand: "ja!",
    caloriesPer100g: 57,
    proteinPer100g: 4.3,
    carbsPer100g: 5.5,
    fatPer100g: 1.5,
    aliases: ["joghurt", "jogurt", "rewe joghurt", "naturjoghurt"],
  },
  {
    id: "brand:gut-guenstig-joghurt-natur-1-5",
    name: "Joghurt natur 1,5%",
    brand: "Gut & Günstig",
    caloriesPer100g: 57,
    proteinPer100g: 4.3,
    carbsPer100g: 5.5,
    fatPer100g: 1.5,
    aliases: ["joghurt", "jogurt", "edeka joghurt", "naturjoghurt"],
  },
  {
    id: "brand:weihenstephan-joghurt-mild-1-5",
    name: "Joghurt mild 1,5%",
    brand: "Weihenstephan",
    caloriesPer100g: 63,
    proteinPer100g: 4,
    carbsPer100g: 5.7,
    fatPer100g: 1.5,
    aliases: ["joghurt", "jogurt", "weihenstephan joghurt", "naturjoghurt"],
  },
  {
    id: "common:haferflocken",
    name: "Haferflocken",
    brand: "Standard",
    caloriesPer100g: 370,
    proteinPer100g: 13.5,
    carbsPer100g: 58.7,
    fatPer100g: 7,
    aliases: ["oats", "haf"],
  },
  {
    id: "brand:koelln-haferflocken",
    name: "Blütenzarte Haferflocken",
    brand: "Kölln",
    caloriesPer100g: 372,
    proteinPer100g: 13.5,
    carbsPer100g: 58.7,
    fatPer100g: 7,
    aliases: ["haferflocken", "oats", "koelln", "kölln"],
  },
  {
    id: "brand:ja-haferflocken",
    name: "Haferflocken",
    brand: "ja!",
    caloriesPer100g: 370,
    proteinPer100g: 13.5,
    carbsPer100g: 58.7,
    fatPer100g: 7,
    aliases: ["haferflocken", "oats", "rewe haferflocken"],
  },
  {
    id: "brand:gut-guenstig-haferflocken",
    name: "Haferflocken",
    brand: "Gut & Günstig",
    caloriesPer100g: 370,
    proteinPer100g: 13.5,
    carbsPer100g: 58.7,
    fatPer100g: 7,
    aliases: ["haferflocken", "oats", "edeka haferflocken"],
  },
  {
    id: "brand:biozentrale-haferflocken",
    name: "Haferflocken",
    brand: "Biozentrale",
    caloriesPer100g: 372,
    proteinPer100g: 13.5,
    carbsPer100g: 58.7,
    fatPer100g: 7,
    aliases: ["haferflocken", "oats", "bio haferflocken"],
  },
  {
    id: "common:banane",
    name: "Banane",
    brand: "Standard",
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 23,
    fatPer100g: 0.3,
    aliases: ["banana"],
  },
  {
    id: "common:apfel",
    name: "Apfel",
    brand: "Standard",
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 14,
    fatPer100g: 0.2,
    aliases: ["apple"],
  },
  {
    id: "common:paprika-gruen",
    name: "Paprika grün",
    brand: "Standard",
    caloriesPer100g: 20,
    proteinPer100g: 0.9,
    carbsPer100g: 4.6,
    fatPer100g: 0.2,
    aliases: ["paprika", "paprika gruen", "grüne paprika", "gruene paprika", "paprikaschote"],
  },
  {
    id: "common:paprika-rot",
    name: "Paprika rot",
    brand: "Standard",
    caloriesPer100g: 43,
    proteinPer100g: 1.3,
    carbsPer100g: 6.4,
    fatPer100g: 0.5,
    aliases: ["paprika", "rote paprika", "paprikaschote rot", "red bell pepper"],
  },
  {
    id: "common:paprika-gelb",
    name: "Paprika gelb",
    brand: "Standard",
    caloriesPer100g: 27,
    proteinPer100g: 1,
    carbsPer100g: 5.3,
    fatPer100g: 0.2,
    aliases: ["paprika", "gelbe paprika", "paprikaschote gelb", "yellow bell pepper"],
  },
  {
    id: "common:reis-gekocht",
    name: "Reis gekocht",
    brand: "Standard",
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28,
    fatPer100g: 0.3,
    aliases: ["reis", "rice"],
  },
  {
    id: "brand:uncle-bens-express-reis-basmati-gekocht",
    name: "Express Reis Basmati gekocht",
    brand: "Ben's Original",
    caloriesPer100g: 159,
    proteinPer100g: 3.2,
    carbsPer100g: 33,
    fatPer100g: 1.4,
    aliases: ["reis", "rice", "bens original", "uncle bens", "express reis", "basmati"],
  },
  {
    id: "brand:oryza-basmati-gekocht",
    name: "Basmati Reis gekocht",
    brand: "Oryza",
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28,
    fatPer100g: 0.3,
    aliases: ["reis", "rice", "oryza", "basmati"],
  },
  {
    id: "brand:reis-fit-basmati-gekocht",
    name: "Basmati Reis gekocht",
    brand: "Reis-Fit",
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28,
    fatPer100g: 0.3,
    aliases: ["reis", "rice", "reis fit", "reis-fit", "basmati"],
  },
  {
    id: "common:nudeln-gekocht",
    name: "Nudeln gekocht",
    brand: "Standard",
    caloriesPer100g: 158,
    proteinPer100g: 5.8,
    carbsPer100g: 31,
    fatPer100g: 0.9,
    aliases: ["nudeln", "pasta"],
  },
  {
    id: "brand:barilla-spaghetti-gekocht",
    name: "Spaghetti gekocht",
    brand: "Barilla",
    caloriesPer100g: 158,
    proteinPer100g: 5.8,
    carbsPer100g: 31,
    fatPer100g: 0.9,
    aliases: ["nudeln", "pasta", "spaghetti", "barilla"],
  },
  {
    id: "brand:buitoni-spaghetti-gekocht",
    name: "Spaghetti gekocht",
    brand: "Buitoni",
    caloriesPer100g: 158,
    proteinPer100g: 5.8,
    carbsPer100g: 31,
    fatPer100g: 0.9,
    aliases: ["nudeln", "pasta", "spaghetti", "buitoni"],
  },
  {
    id: "brand:ja-nudeln-gekocht",
    name: "Nudeln gekocht",
    brand: "ja!",
    caloriesPer100g: 158,
    proteinPer100g: 5.8,
    carbsPer100g: 31,
    fatPer100g: 0.9,
    aliases: ["nudeln", "pasta", "rewe nudeln"],
  },
  {
    id: "common:kartoffeln",
    name: "Kartoffeln gekocht",
    brand: "Standard",
    caloriesPer100g: 86,
    proteinPer100g: 1.9,
    carbsPer100g: 20,
    fatPer100g: 0.1,
    aliases: ["kartoffel", "potato"],
  },
  {
    id: "common:haehnchenbrust",
    name: "Hähnchenbrust",
    brand: "Standard",
    caloriesPer100g: 110,
    proteinPer100g: 23,
    carbsPer100g: 0,
    fatPer100g: 1.5,
    aliases: ["hähnchen", "haehnchen", "huhn", "chicken breast"],
  },
  {
    id: "brand:wiesenhof-haehnchenbrust",
    name: "Hähnchenbrust",
    brand: "Wiesenhof",
    caloriesPer100g: 110,
    proteinPer100g: 23,
    carbsPer100g: 0,
    fatPer100g: 1.5,
    aliases: ["hähnchen", "haehnchen", "huhn", "chicken breast", "wiesenhof"],
  },
  {
    id: "brand:gut-guenstig-haehnchenbrust",
    name: "Hähnchenbrust",
    brand: "Gut & Günstig",
    caloriesPer100g: 110,
    proteinPer100g: 23,
    carbsPer100g: 0,
    fatPer100g: 1.5,
    aliases: ["hähnchen", "haehnchen", "huhn", "chicken breast", "edeka hähnchen"],
  },
  {
    id: "common:thunfisch",
    name: "Thunfisch im eigenen Saft",
    brand: "Standard",
    caloriesPer100g: 116,
    proteinPer100g: 25.5,
    carbsPer100g: 0,
    fatPer100g: 1,
    aliases: ["thunfisch", "tuna"],
  },
  {
    id: "brand:saupiquet-thunfisch-eigener-saft",
    name: "Thunfisch im eigenen Saft",
    brand: "Saupiquet",
    caloriesPer100g: 116,
    proteinPer100g: 25.5,
    carbsPer100g: 0,
    fatPer100g: 1,
    aliases: ["thunfisch", "tuna", "saupiquet"],
  },
  {
    id: "brand:followfish-thunfisch-eigener-saft",
    name: "Thunfisch im eigenen Saft",
    brand: "followfish",
    caloriesPer100g: 116,
    proteinPer100g: 25.5,
    carbsPer100g: 0,
    fatPer100g: 1,
    aliases: ["thunfisch", "tuna", "followfish"],
  },
  {
    id: "brand:ja-thunfisch-eigener-saft",
    name: "Thunfisch im eigenen Saft",
    brand: "ja!",
    caloriesPer100g: 116,
    proteinPer100g: 25.5,
    carbsPer100g: 0,
    fatPer100g: 1,
    aliases: ["thunfisch", "tuna", "rewe thunfisch"],
  },
  {
    id: "common:ei",
    name: "Ei",
    brand: "Standard",
    caloriesPer100g: 155,
    proteinPer100g: 13,
    carbsPer100g: 1.1,
    fatPer100g: 11,
    aliases: ["eier", "egg"],
  },
];
